### ISSUE TITLE
Compile issues - 'RSIntegrationFactory.h' file not found

### ISSUE THREAD

**Issue by kekami** [rudderlabs/rudder-sdk-react-native#116]
Hello,

I'm trying to integrate the RudderStack RN sdk into our project, however I'm running into compile issues.

In `RNRudderAnalytics.h`, XCode can't find the header file for `RSIntegrationFactory.h`.

Is this something you can reproduce on your end?

**Comment by desusai7** [comment]
Hey @kekami  & @riepmore , 

Can you guys please share the version of `@rudderstack/rudder-sdk-react-native` (from package-lock.json) and the version of Rudder iOS SDK `Rudder` (from ios/podfile.lock) you are on?

Also, can you please try the following steps once and let us know if they are of any help ?

1. re-install the node_modules
2. navigate to ios folder of your app 
3.  execute the command `rm podfile.lock && pod deintegrate && pod install`

**Comment by riepmore** [comment]
Hello @desusai7 

Deintegrate Pods didn't worked for me.

My package version:
`"@rudderstack/rudder-sdk-react-native": "^1.4.0",`

In Podifle i have:
```
 - RNRudderSdk (1.0.0)
 - Rudder (2.0.1)

```

**Comment by desusai7** [comment]
Hey @riepmore , 
Can you please confirm if you were able to see the file Pods/Rudder/Sources/Classes/Public/RSIntegration.h  in your project ?

**Comment by kekami** [comment]
@desusai7 Hello, I can confirm, looking for the `Pods/Rudder/Sources/Classes/Public/RSIntegration.h` it appears that I am lacking the entire `Public` folder. I also tried `pod upgrade RNRudderSdk` to 2.0.2 but same issue there.

![Screenshot 2022-05-25 at 13 33 37](https://user-images.githubusercontent.com/24361798/170252915-47c2cf53-7f5b-4305-91b3-b190be5ae938.png)

**Comment by desusai7** [comment]
Hey @kekami , We had identified the reason for the issue and we had fixed it in the linked PR, we will release it shortly

**Comment by desusai7** [comment]
Hey @kekami & @riepmore , 
Can you please upgrade to the version `1.4.1` of `@rudderstack/rudder-sdk-react-native`, we had fixed the issue in this version.

**Comment by riepmore** [comment]
Hey @desusai7 

It work perfectly now, thanks a lot for your help !
