### ISSUE TITLE
Docs don't match code

### ISSUE THREAD

**Issue by kevinjamescasey** [rudderlabs/rudder-sdk-react-native#133]
This documentation says to use `trackLifecycleEvents`:
https://www.rudderstack.com/docs/sources/sdks/rudderstack-react-native-sdk/#initializing-the-rudderstack-client

But this code uses `trackAppLifecycleEvents`:
https://github.com/rudderlabs/rudder-sdk-react-native/blob/master/src/NativeBridge.ts#L11

**Comment by 1abhishekpandey** [comment]
@kevinjamescasey Sorry for any trouble. Actually there is a problem with the doc snippet and we are going to update that soon. Thanks for bringing this up.

**Comment by 1abhishekpandey** [comment]
We have updated our React-Native documents. Again, thanks for notifying us.
