### ISSUE TITLE
Expo Config Plugin

### ISSUE THREAD

**Issue by nandorojo** [rudderlabs/rudder-sdk-react-native#144]
It would be nice to add an Expo config plugin for the Android step. It's a simple JS file for Expo users that configures the native project.

The iOS app doesn't need one.

**Comment by pallabmaiti** [comment]
Dear @nandorojo, please feel free to contribute to our codebase. You can raise a PR, and we will review & merge. Please make sure to sign this [CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement), and your commit should be squashed into 1 only.

**Comment by sam1463** [comment]
@nandorojo is this for the `mavenCentral()` repository part? Is that not automatically set by Expo's autolinking?

**Comment by robert-nash** [comment]
I am trying to build an expo project myself but the builds are failing on Android. I wonder if anyone could confirm whether a config plugin is required for this to work?

**Comment by robert-nash** [comment]
In response to my own question, it appears to be possible to use this package with eas build without a config plugin. On Expo 47 it appears to be necessary to set compileSdkVersion to 33 to prevent build errors on Android. This should be fixed in Expo 48. I added the following to my app.config.js

```
 plugins: [
        [
            "expo-build-properties",
            {
                android: {
                    // TODO: Remove when installing SDK 48
                    compileSdkVersion: 33,
                    targetSdkVersion: 33,
                    buildToolsVersion: "33.0.0",
                },
            },
        ],
    ]
```

**Comment by bardisg** [comment]
@1abhishekpandey has this been resolved now?

**Comment by 1abhishekpandey** [comment]
Hey @robert-nash, 
Is the issue resolved?

**Comment by robert-nash** [comment]
Yes I managed to get it to work with the configuration described here (https://github.com/rudderlabs/rudder-sdk-react-native/issues/144#issuecomment-1452125361). I have not tried it myself but I expect that with Expo 48 there should now be no configuration required.
