### ISSUE TITLE
Support for react-native <0.60 (pre-autolink)

### ISSUE THREAD

**Issue by jjblumenfeld** [rudderlabs/rudder-sdk-react-native#17]
Is it possible to use the library with react-native 0.59 or earlier? Tthe install instructions rely on autolinking but that is not expected to work on older react-native installs.
Can you add instructions for getting this to work with earlier versions?

**Comment by desusai7** [comment]
Ideally on versions less than `0.60` we should be manually linking the dependencies as `react-native link @rudderstack/rudder-sdk-react-native`. 
But we do not support our SDK with React-Native versions 0.59 and earlier
