### ISSUE TITLE
BUG : documentation link in this project's readme file is broken (404)

### ISSUE THREAD

**Issue by sam1463** [rudderlabs/rudder-sdk-react-native#174]
**Describe the bug**
Please provide the following information:
Title says it all - docs link is broken

**Which platform is the issue occurring on**
n/a

**To Reproduce**
click the link to documentation at the bottom of the readme

**Expected behavior**
Opens a link to docs

**Screenshots**

**Comment by 1abhishekpandey** [comment]
Thank you for bringing this to our attention. We will update the readme file.

**Comment by 1abhishekpandey** [comment]
We have updated the readme file. Thanks again for notifying us about this issue.
