### ISSUE TITLE
BUG : Unable to install package due to dependancy - React Native 0.41.2

### ISSUE THREAD

**Issue by virajverlekar-tm** [rudderlabs/rudder-sdk-react-native#179]
**Describe the bug**
Getting following error on npm install

npm ERR! Found: react-native@0.70.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.70.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from @rudderstack/rudder-sdk-react-native@1.6.2
npm ERR! node_modules/@rudderstack/rudder-sdk-react-native
npm ERR!   @rudderstack/rudder-sdk-react-native@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Which platform is the issue occurring on**
Is the error occurring on:

- [x] Android

**To Reproduce**
Steps to reproduce the behaviour:
1. npm i @rudderstack/rudder-sdk-react-native

**Expected behavior**
React Native Rudderstack installed

**Screenshots**
<img width="596" alt="Screenshot 2023-02-28 at 12 37 09 AM" src="https://user-images.githubusercontent.com/89062692/221659229-3648301c-59d6-41f2-bf77-d3d9c29d5a83.png">

**Version of the _React-Native_ SDK**
The version of the Rudder React-Native SDK - v1.6.2

**Framework version of the SDK**
The version of the React-Native framework used - “react-native”: v0.70.2

**Comment by 1abhishekpandey** [comment]
Could you please share the versions of `npm` and `node`?

**Comment by 1abhishekpandey** [comment]
Can you also provide information on whether you have attempted to install the dependency in the sample app and, if so, which tools you used (such as expo)?

**Comment by virajverlekar-tm** [comment]
node -v
v18.11.0
npm -v
8.19.2

**Comment by virajverlekar-tm** [comment]
I have tried using React Native CLI.
Yes, i did try installing the dependency in the sample app but got the same error.

**Comment by 1abhishekpandey** [comment]
Could you please try updating your node and npm version, `npm` to `9.4.0` and node to `v16.15.1` and check if the issue still persists? Please let me know the results.

Just to let you know, I tried installing the dependency using the `npm` and `node` versions I mentioned (i.e., 9.4.0 and v16.15.1 respectively), and the installation was successful.

**Comment by 1abhishekpandey** [comment]
Thank you for providing the information. I will further investigate with the provided information and keep you updated with the results.

**Comment by 1abhishekpandey** [comment]
As a tactical interim fix please use overrides in your package.json:
```
"overrides": {
      "react-native": "0.70.2"
}
```

**Comment by virajverlekar-tm** [comment]
I tried by updating node & setting up new react native project but got the same error.

Steps:
1. npx react-native init SampleProject
2. npm i @rudderstack/rudder-sdk-react-native

<img width="602" alt="Screenshot 2023-02-28 at 8 27 16 PM" src="https://user-images.githubusercontent.com/89062692/221891792-e713b79a-def3-4057-b5c2-e238b75afff8.png">

**Versions**
React Native:
v0.71.3

React Native Rudderstack:
v1.6.2

node:
v19.7.0

npm:
9.5.0

java:
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

I have found dependency for 0.41.2 in rudderstack package-lock.json
https://raw.githubusercontent.com/rudderlabs/rudder-sdk-react-native/develop/package-lock.json
![image](https://user-images.githubusercontent.com/89062692/221893756-0ff3e229-f30c-48c2-a87b-91fc3c52e5a1.png)


The installation works if i add the following code though
"overrides": {
    "@rudderstack/rudder-sdk-react-native": {
        "react-native": "0.70.2"
    }
}

**Comment by 1abhishekpandey** [comment]
The `react-native` version should be resolved automatically since we haven't locked it to a specific version like `0.41.2`. The dependency range is specified as `^0.41.2`, which should allow it to resolve to any version until the next major version. Therefore, `@0.70.2` is within that range and should be resolved without any issues. 

Unable to figure out the error in your case. Can you please try one additional step:
- Clone our repository and just try running `npm i` and check if still, you're getting the same error or not.
- Refer to our repo: https://github.com/rudderlabs/rudder-sdk-react-native/tree/master.

**Comment by virajverlekar-tm** [comment]
If I clone the repo, npm install works but throws the same thing as a warning
<img width="616" alt="Screenshot 2023-03-02 at 4 50 21 PM" src="https://user-images.githubusercontent.com/89062692/222415631-3d6a2d6c-0214-436e-af57-e9a27ad85874.png">

But if i go to the example & try npm install, it throws the same error.
<img width="861" alt="Screenshot 2023-03-02 at 4 56 56 PM" src="https://user-images.githubusercontent.com/89062692/222416249-9bd4e24b-c4a7-4c25-822e-80fc916d771c.png">

**Comment by 1abhishekpandey** [comment]
Hey @virajverlekar-tm, 
Please run this command at your local system and let me know the output:
```
npm config get legacy-peer-deps
```

**Comment by virajverlekar-tm** [comment]
```
$ npm config get legacy-peer-deps
false
```

**Comment by 1abhishekpandey** [comment]
We are currently in the process of providing a solution. In the meantime, you may utilize the previously suggested steps.

> As a tactical interim fix please use overrides in your package.json:
``` 
"overrides": {
      "react-native": "0.70.2"
}
```

**Comment by 1abhishekpandey** [comment]
Hey @virajverlekar-tm,
The solution has been implemented. Kindly update to the latest version of @rudderstack/rudder-sdk-react-native" (v1.6.3) and inform us if it resolves your problem.

**Comment by virajverlekar-tm** [comment]
Working fine on v1.6.3
