### ISSUE TITLE
BUG : Typechecking a consumer project with `strict: true` raises errors in the SDK package

### ISSUE THREAD

**Issue by rtrembecky** [rudderlabs/rudder-sdk-react-native#180]
**Describe the bug**

When a consumer of the `@rudderstack/rudder-sdk-react-native` package type-checks their project with `"strict": true` option on in `tsconfig.json`, errors in `node_modules` are raised.

I believe there are two factors to consider:
1. the actual errors
   - you can turn the flag in the repo on yourself and fix the errors
2. the files that are published
    - you probably shouldn't ship raw `.ts` files and should build `.js`+`.d.ts` and publish a package of those instead
    - shipping `.ts` means the consumer needs to compile the package themselves, which shouldn't need to happen

More context potentially in the original Slack thread: https://rudderstack.slack.com/archives/C01E4PLB135/p1677518563247609

**Which platform is the issue occurring on**

- [ ] Android
- [ ] iOS
- [x] Both Android and iOS - related to platform-agnostic setup

**To Reproduce**
Steps to reproduce the behavior - in a consumer project:

1. `yarn add @rudderstack/rudder-sdk-react-native`
2. add `"strict": true` to the `compilerOptions` in `tsconfig.js`
3. add initialization snippet to `src/App.tsx`
4. `yarn tsc`

**Expected behavior**
I should see errors only from the consumer code.

**Screenshots**

**Version of the _React-Native_ SDK**
1.6.2

**SDK initialization snippet**
await rudderClient.setup('OUR_KEY', {
  dataPlaneUrl: 'OUR_URL',
})

**Framework version of the SDK**
react-native: 0.71.1

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
The snippet used is right from the RudderStack dashboard ✅

**Comment by 1abhishekpandey** [comment]
Thank you for bringing this to our attention. We will investigate the issue.

**Comment by 1abhishekpandey** [comment]
Hey @rtrembecky,
The solution has been implemented. Kindly update to the latest version of @rudderstack/rudder-sdk-react-native" (v1.6.3) and inform us if it resolves your problem.

**Comment by sidekick-richard** [comment]
all good after upgrading to v1.6.3, thanks for the work 🙂
