### ISSUE TITLE
`alias` overload type failing

### ISSUE THREAD

**Issue by nandorojo** [rudderlabs/rudder-sdk-react-native#182]
Skipping the issue template since this is a basic type issue. For some reason, `yarn tsc` is upset about this in Rudderstack's types.

<img width="1105" alt="Screenshot 2023-03-03 at 12 48 03 PM" src="https://user-images.githubusercontent.com/13172299/222791669-a2c86b72-5480-4b86-ad06-94248e1c5ce2.png">

The issue is, the `alias` implementation's second parameter allows `Record | null` and is missing ` | string` from the overload above. 

Adding this to the second instance of `alias`'s second parameter fixes it:

```ts
options: Record<string, unknown> | null | string = null
```

Notice that `string` is also a possibility now. This is on version `1.6.2`.

## Fix

Here's a `patch-package` fix. I'll open a PR too.

```patch
diff --git a/node_modules/@rudderstack/rudder-sdk-react-native/src/RudderClient.ts b/node_modules/@rudderstack/rudder-sdk-react-native/src/RudderClient.ts
index 065ae16..cb4d59d 100644
--- a/node_modules/@rudderstack/rudder-sdk-react-native/src/RudderClient.ts
+++ b/node_modules/@rudderstack/rudder-sdk-react-native/src/RudderClient.ts
@@ -189,7 +189,7 @@ async function group(
 
 // wrapper for `alias` method
 async function alias(previousId: string, userId: string | Record<string, unknown>): Promise<void>;
-async function alias(newId: string, options: Record<string, unknown> | null = null) {
+async function alias(newId: string, options: Record<string, unknown> | null | string = null) {
   if (newId == undefined) {
     logWarn("alias: Mandatory field 'newId' missing");
     return;
```

**Comment by nandorojo** [comment]
PR at #183

**Comment by rtrembecky** [comment]
also related to #180

**Comment by 1abhishekpandey** [comment]
Thanks for raising the issue. We'll look into this and get back to you.

**Comment by 1abhishekpandey** [comment]
Hey @nandorojo 
The solution has been implemented. Kindly update to the latest version of `@rudderstack/rudder-sdk-react-native"` (v1.6.3) and inform us if it resolves your problem.
Thanks again for your contribution.
