### ISSUE TITLE
putDeviceToken is not public for rudderContext

### ISSUE THREAD

**Issue by enahum** [rudderlabs/rudder-sdk-react-native#19]
It seems that you guys updated the underline library and now ` putDeviceToken` is not a public method and is breaking the RN lib.

```
RNRudderSdkModule.java:102: error: putDeviceToken(String) is not public in RudderContext; cannot be accessed from outside package
            rudderContext.putDeviceToken(token);
```

This is blocking us from cutting a new build. (Mattermost)

**Comment by arnab-p** [comment]
Thanks, @enahum, for the issue. We're working on this. We'll release a fix shortly.

**Comment by arnab-p** [comment]
Fixed in: https://github.com/rudderlabs/rudder-sdk-react-native/pull/20
