### ISSUE TITLE
What is the best repo to look at for contributing a Flutter SDK?

### ISSUE THREAD

**Issue by ramkumarkb** [rudderlabs/rudder-sdk-react-native#2]
Hello,

I would like to contribute towards a Flutter SDK for RudderStack. What would be the best repo to look at as a reference - is it the RN repo (am therefore logging this issue here).

Any other tips or pointers towards this would also be helpful.

Thank you,

**Comment by SumanthPuram** [comment]
Thanks for the initiative. This would be really great to have. You can use our react-native SDK as the reference.

This is another repo for Segment, not sure how well it is maintained. 

https://github.com/FaisalAbid/segment-analytics-flutter

**Comment by SumanthPuram** [comment]
@ramkumarkb Did you get a chance to look at this?

**Comment by ramkumarkb** [comment]
@SumanthPuram - Not yet. But I will be taking a look in the coming days.

**Comment by adnsio** [comment]
Hi @ramkumarkb, I'm working on it: https://github.com/adnsio/flutter-rudder

**Comment by arnab-p** [comment]
@ramkumarkb We've released the Flutter SDK. You can check the [Github Repository](https://github.com/rudderlabs/rudder-sdk-flutter) and the [documentation](https://docs.rudderstack.com/stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk)
