### ISSUE TITLE
Feature Request: Add logging of events in console

### ISSUE THREAD

**Issue by Amaimersion** [rudderlabs/rudder-sdk-react-native#220]
**Is your feature request related to a problem? Please describe.**
During debugging I need to check what events (what names and what parameters) were sent by RudderStack SDK. At the moment it can be done only by opening RudderStack Control Plane and watching live events. But it is not convenient.

**Describe the solution you'd like**
Add logging of events (event type, event name, event parameters) in console at `DEBUG` or `VERBOSE` level.

**Describe alternatives you've considered**
Segment SDK logs all events that were sent.

**Comment by 1abhishekpandey** [comment]
Please refer to our doc: [Debugging](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#debugging). Once the logging feature is enabled, all the events and their respective parameters will be visible in the console. Please let me know if I can assist you in any other way.

Code snippet to enable the logging:
`await rudderClient.setup(WRITE_KEY, {
  dataPlaneUrl: DATA_PLANE_URL,
  logLevel: RUDDER_LOG_LEVEL.DEBUG, // or VERBOSE
})
`

**Comment by Amaimersion** [comment]
I tried both `DEBUG` and `VERBOSE` and the only messages that get logged in the console are:

```
 LOG  RudderSDK: Debug: Initializing Rudder RN SDK version: 1.7.1
 LOG  RudderSDK: Debug: setup: created config
 LOG  RudderSDK: Debug: setup: setup completed
```

**Comment by 1abhishekpandey** [comment]
To view the Android log open the `android` directory of your React-Native project in the Android Studio and similarly for iOS open the `<Name of the iOS project>.xcworkspace` (e.g., Example.xcworkspace) in the XCode.
After that, all the logs would be visible in the respective console.

**Comment by Amaimersion** [comment]
Unfortunately I'm not using neither Android Studio nor XCode. I'm using VSCode with terminal. In the terminal I'm executing `react-native start` and `npx react-native run-android`. That's it, and it was perfectly enough for everything including logs. All tools I have do logging via `console.log`, Segment also doing that. This way I can see everything in my terminal. Does it possible that RudderStack SDK also will do logging using `console.log`?

**Comment by 1abhishekpandey** [comment]
It appears that Segment has implemented their React Native SDKs directly, allowing them to support this feature. In contrast, the RudderStack React Native SDK acts as a wrapper for the native Rudder Android and iOS SDKs, and currently there is no built-in capability to redirect the logs from the native SDKs to the main terminal.

However, I will pass on your feature request to our team for consideration. In the meantime, I recommend exploring the use of Android Studio and Xcode for viewing the logs, as they provide comprehensive debugging capabilities for Android and iOS development.

**Comment by Amaimersion** [comment]
Thank you!
