### ISSUE TITLE
Automatic session tracking?

### ISSUE THREAD

**Issue by ctscoville** [rudderlabs/rudder-sdk-react-native#223]
Does the React Native SDK support automatic session tracking? I see in the docs for session tracking that the iOS, Android, and Javascript SDKs support automatic session tracking, which is enabled by default.  But in our React Native SDK integration, we're not seeing the `Start Session` and `End Session` events events showing up in Amplitude, so I'm wondering if this is something that is just not implemented yet for the React Native SDK, or if this should work.

**Comment by 1abhishekpandey** [comment]
Session tracking is currently not available in our React-Native SDKs. However, we have started implementing session tracking in React-Native, and we expect to complete it soon.

**Comment by ctscoville** [comment]
Thanks for the quick reply. That's the information I was looking for.  We'll keep an eye out for a future update with that added.  Thanks! 
Closing this for now since it answered my question.

**Comment by 1abhishekpandey** [comment]
Hey @ctscoville,
We've launched the React Native SDK version [1.8.0](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.8.0) with the session tracking feature. Please utilize this version to access the session tracking feature.
For more info, refer to our doc:
1. https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#tracking-user-sessions
2. https://www.rudderstack.com/docs/sources/event-streams/sdks/session-tracking/
