### ISSUE TITLE
Nothing is being sent

### ISSUE THREAD

**Issue by donaldparker** [rudderlabs/rudder-sdk-react-native#24]
Hello I'm in the process of adding Rudderstack to our React Native project.  I've followed the step outlined in[ this document](https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk) but we are not receiving any events.  

After tailing the logs on our server and not seeing any traffic, and knowing React Native network inspections with my current set up is not possible,  I decided to stand up a little node server to catch all traffic with cors headers for all origins.  Not a single request from the rudderClient is making it to the server. 

Here is my implementation 
```
const rudderConfig = {
  dataPlaneUrl: "http://localhost:3000",
  trackAppLifecycleEvents: true,
  logLevel: RUDDER_LOG_LEVEL.DEBUG
};

rudderClient.setup(Config.rudderstack.writeKey, rudderConfig).then(() => {
  console.log("this message is logged with the correct info", Config.rudderstack.writeKey, rudderConfig);
});

export const setUser = (user: User): void => {
  const userProps = {
    ...redacted
  };
  analytics().setUserId(user.userId);  //seen in firebase
  analytics().setUserProperties(userProps);  //seen in firebase
  rudderClient.identify(user.userId, userProps);  //nothing here
};

export const trackScreen = (screenName: string): void => {
  analytics().setCurrentScreen(screenName); // seen in firebase
  rudderClient.screen(screenName); // nothing here
};


export const trackEvent = (
  eventName: string,
  params?: { [name: string]: string } | undefined
): void => {
  const eventData = {
    ...params,
    platform: Platform.OS,
    version: Platform.Version.toString()
  };
  analytics().logEvent(eventName, eventData); // Data seen in firebase
  rudderClient.track(eventName, eventData); // nothing here
};
```

I've also removed the pods directory
```
cd ios 
rm -rf Pods
pod install 
```
One other NIT, is the typescript signatures say a Promise<void> is returned but the actual implementation does not have a return value.

**Comment by desusai7** [comment]
Hey @donaldparker,

Seems like those events are made even before RudderStack RN SDK got initialize completely. 

As you are not using the `await` keyword before the setup call as mentioned in the docs [here](https://docs.rudderstack.com/stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk#initializing-the-rudderstack-client).

Can you please try adding `await` and check if the events flow to RudderStack?

And also we are adding a log statement saying that the events will be dropped in case where events are sent even before the SDK is initialized.

**Comment by desusai7** [comment]
Closing this issue, for now, feel free to re-open it if the issue still persists.
