### ISSUE TITLE
BUG : iOS build error

### ISSUE THREAD

**Issue by andrewdazs** [rudderlabs/rudder-sdk-react-native#248]
**Describe the bug**

When I try build the iOS app with XCode the follow error accurs:

`No visible @interface for 'RSClient' declares the selector 'reset:'`

This happen on line 146 in `RNRudderSdkModule` file.

**Which platform is the issue occurring on**

- [ ] Android
- [x] iOS
- [ ] Both Android and iOS

**To Reproduce**

1. Install rudder with `yarn add @rudderstack/rudder-sdk-react-native`
2. Run `pod install`
3. Build the project with XCode
4. See the error

**Expected behavior**
Build the iOS app with success

**Screenshots**
<img width="2406" alt="Screenshot 2023-09-20 at 16 09 45" src="https://github.com/rudderlabs/rudder-sdk-react-native/assets/21009570/c1a18230-7262-476c-bc3e-e0e1ab06da37">

**Version of the _React-Native_ SDK**

- "@rudderstack/rudder-sdk-react-native": "^1.9.0"
- RNRudderSdk (1.9.0):
    - React
    - Rudder (< 2.0.0, >= 1.9.2)

**Framework version of the SDK**
“react-native”: v0.65.2

**Comment by 1abhishekpandey** [comment]
Hey @andrewdazs,
Please update the `rudder-sdk-react-native` package to the latest version `1.9.1` and let us know if it solves the iOS build issue or not.

**Comment by andrewdazs** [comment]
It works, thanks!

Also needed to change the ios platform from 11 to 12.4 and add `'RSCrashReporter', :modular_headers => true` in Podfile.

**Comment by 1abhishekpandey** [comment]
Thanks for the confirmation.
We have updated our [doc](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#installing-the-react-native-sdk) to add this `'RSCrashReporter', :modular_headers => true` in the Podfile.
