### ISSUE TITLE
BUG : iOS client stops working after reloading development bundle

### ISSUE THREAD

**Issue by elliotdickison** [rudderlabs/rudder-sdk-react-native#262]
**Describe the bug**

After reloading the JS development bundle from Metro on iOS the rudder client stops working properly. All methods are calleable and resolve without error (I've tried `rudder.setup`, `rudder.reset`, `rudder.identify`, `rudder.track`, and `rudder.screen`), but no events are sent from the device and `rudder.getRudderContext` returns `undefined` even after `rudder.identify` has been called. Restarting the development app fixes the issue (swipe up from app switcher to close and tap icon to reopen).

**Which platform is the issue occurring on**
Is the error occurring on:

- [ ] Android
- [x] iOS
- [ ] Both Android and iOS

**To Reproduce**
Steps to reproduce the behaviour:

1. Setup the RudderStack SDK, identify a user, print out context, and flush (for testing).

```js
import rudder from "@rudderstack/rudder-sdk-react-native"

async function go() {

  await rudder.setup(<write key>, {
    dataPlaneUrl: <data plane URL>,
    controlPlaneUrl: <control plane URL>,
    recordScreenViews: false,
    trackAppLifecycleEvents: false,
  })

  await rudder.identify(<user ID>, <custom traits>, {})

  const context = await rudder.getRudderContext()
  
  await rudder.flush()

  console.log("context", context)
}

go().catch(error => console.error(error))
```

2. Open up your control plane, start viewing live events, and then open your development app. Note that when the app is loaded the identify call is logged in the live event view and context is printed out in the local development console.

3. Make a change to the file and reload the bundle from metro (e.g. press "r" from your metro terminal window).

4. Note that the identify call does not show up in the live view and context is logged as undefined

5. Restart the app and the behavior is fixed.
 
**Expected behavior**

I would expect the rudder client to be resilient to reloading the development bundle on iOS (like it is on Android).

**Version of the _React-Native_ SDK**

This issue does _not_ impact 1.7.0. We experienced it after upgrading to 1.9.1 and 1.10.0. 

**SDK initialisation snippet**

See steps to reproduce the behavior.

**Framework version of the SDK**

`react-native@0.72.3`

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**

Done

**Comment by 1abhishekpandey** [comment]
Hey @elliotdickison,
Thank you for bringing up the issue and providing the steps to reproduce it. I've been able to replicate it on my end, and it appears to impact the iOS development build. We will work on finding a solution.

**Comment by 1abhishekpandey** [comment]
We have addressed this issue in `rudder-sdk-react-native` version [1.11.1](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.11.1). Please utilise this version.

Please note that after reloading your Android and iOS app, you will need to reinitialize the Rudder React Native SDK before you can send new events.

**Comment by elliotdickison** [comment]
Thanks!!
