### ISSUE TITLE
BUG : Incorrect TypeScript type for getRudderContext

### ISSUE THREAD

**Issue by elliotdickison** [rudderlabs/rudder-sdk-react-native#263]
**Describe the bug**

The `getRudderContext` method is typed as returning `Promise<void>` when it fact it returns something like `Promise<Record<string, unknown> | undefined>` (I'll leave it up to you all whether you can get more specific than `Record<string, unknown>`). The offending line is here: https://github.com/rudderlabs/rudder-sdk-react-native/blob/0fb45714adb28a43554bca59ffd1f00b0bc05412/libs/sdk/src/NativeBridge.ts#L55

**Which platform is the issue occurring on**
Is the error occurring on:

- [ ] Android
- [ ] iOS
- [x] Both Android and iOS

**To Reproduce**

Attempt something like this and watch TypeScript fail to compile:

```
async function getRudderContextTraits() {
  const context = await rudder.getRudderContext()
  return context?.traits
}
```

**Version of the _React-Native_ SDK**

1.10.0

**Comment by 1abhishekpandey** [comment]
Thanks for raising the issue we will look into this.

**Comment by 1abhishekpandey** [comment]
We have addressed this issue in `rudder-sdk-react-native` version [1.11.1](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.11.1). Please utilise this version.
