### ISSUE TITLE
BUG : @rudderstack/rudder-integration-clevertap-react-native tracks only flatobject

### ISSUE THREAD

**Issue by numandev1** [rudderlabs/rudder-sdk-react-native#286]
**Describe the bug**

# Event Payload

```
{
    "country": "sa",
    "deviceId": "1573",
    "items": [
        {
            "index": 0,
            "item_id": "765",
            "item_name": "Freshly Hot Paprika 99 gr",
            "item_name_ar": "فرشلي بابريكا فلفل حار 99 جم",
            "price": 1000,
            "quantity": 1
        },
        {
            "index": 1,
            "item_id": "894",
            "item_name": "Delicio French Dressing 267 ml",
            "item_name_ar": "ديلسيو صوص فرنسي 267 مل",
            "price": 775,
            "quantity": 1
        }
    ],
    "latitude": 30.818583652580216,
    "location_lat": "24.713628555388915",
    "location_lon": "46.67532032355666",
    "longitude": 73.46148821712511,
    "referrer": "cart_tab",
    "selected_language": "en",
    "storeId": "22",
    "user_id": "303"
}
```

I am calling this track function `rudderClient.track(key, value);` with above payload, + i am using `@rudderstack/rudder-integration-clevertap-react-native` package to send this data into clevertap, all data is going correctly except items as it is array, so it is accepting only flatobject

**Which platform is the issue occurring on**
Is the error occurring on:

- [x] Android
- [x] iOS
- [x] Both Android and iOS

**To Reproduce**
Steps to reproduce the behaviour:

1. Initialise React-Native SDK
2. Make events '....'
3. See the error

**Expected behavior**
how can i track full object not a flatobject only

**Version of the _React-Native_ SDK**
Please provide the following information:
1.7.0

**Framework version of the SDK**
Please indicate the version of the React-Native framework used (e.g., “react-native”: v0.70.6).
0.72.6

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
Confirm that the correct `writeKey` and `dataPlaneUrl` are utilized during SDK initialization.
yes correct

**Comment by 1abhishekpandey** [comment]
Hey @numandev1,
CleverTap only allows sending arrays for the `pushChargedEvent` API, and RudderStack maps to this API when the `Order Completed` event is triggered.

So, if you want to send an array, you have to send the event as the `Order Completed` event and follow this event format: https://www.rudderstack.com/docs/destinations/streaming-destinations/clevertap/#order-completed, where you need to make sure to replace your `"items"` property with `products`.

**Comment by 1abhishekpandey** [comment]
@numandev1 Unfortunately, it is not possible to do that.

**Comment by numandev1** [comment]
@1abhishekpandey From looking into the code it looks like it is possible we add charged detail, are you sure, it is not possible? 
```
Amount
Payment Mode
Charged ID
```

**Comment by 1abhishekpandey** [comment]
I meant to say, in my opinion, it is not possible to send/route any `custom` event to the `pushChargedEvent` API because our E-Commerce spec doesn't allow that.
If you still feel so, then I would suggest opening a feature request to this repo: https://github.com/rudderlabs/rudder-integration-clevertap-android/issues and I would pass it to our team for further consideration.

**Comment by numandev1** [comment]
thanks a lot for you help
