### ISSUE TITLE
BUG : RudderStack and Bugsnag library IOS duplicate symbols

### ISSUE THREAD

**Issue by arnulfosuarez** [rudderlabs/rudder-sdk-react-native#291]
**Describe the bug**
We're starting to implement RudderStack, everything was going well until we get to iOS compilation, we have Bugsnag library to send crash reports directly.
The error es with RSCrashReporter used in this library, some of the errors that is throwing are:

```
❌  /ios/Pods/Bugsnag/Bugsnag/Payload/BugsnagHandledState.h:13:29: redefinition of 'SeverityReasonType'

❌ /ios/Pods/Bugsnag/Bugsnag/Payload/BugsnagHandledState.h:14:5: redefinition of enumerator 'UnhandledException'

...

❌  /ios/Pods/Bugsnag/Bugsnag/include/Bugsnag/BugsnagDeviceWithState.h:19:1: duplicate interface definition for class 'BugsnagDeviceWithState'

❌  /ios/Pods/Bugsnag/Bugsnag/include/Bugsnag/BugsnagDeviceWithState.h:24:51: property has a previous declaration

```

We were using bugsnag-react-native library (the old one) so we tried updating to the lates library but with the same results.
I looked in the repo if there is a way to use the bugsnag library from RudderStack directly, however there is no access to that from React Native

**Which platform is the issue occurring on**
Is the error occurring on:

- [ ] Android
- [X] iOS
- [ ] Both Android and iOS

**To Reproduce**

Have a project where Rudderstack and Bugsnag libraries are used at the same time, after you do the pod install, try to run in ios, it will start compiling and will throw the compile errors.

**Expected behavior**
Both libraries can work side by side or access to the bugsnag library in order to configure it to use my api keys.

**Screenshots**

**Version of the _React-Native_ SDK**
- RudderStack React Native: @rudderstack/rudder-sdk-react-native 1.11.1

Tested with Bugsnag:
- "bugsnag-react-native": "^2.23.10"
- "@bugsnag/react-native": "^7.22.2"

**SDK initialisation snippet**
N/A

**Framework version of the SDK**
- React Native: 0.68.6
- 
**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
N/A

**Comment by 1abhishekpandey** [comment]
Thanks for raising this issue. We are looking into it.

**Comment by 1abhishekpandey** [comment]
We've addressed the compatibility issue between our React Native SDK and BugSnag. Kindly update to the latest SDK version: [rudder-sdk-react-native@1.11.3](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.11.3)

**Comment by gitcommitshow** [comment]
This issue is fixed in the latest release of the [`rudder-sdk-react-native@1.11.3`](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.11.3)
