### ISSUE TITLE
Feature Request: Any roadmap for tvOS support for react-native-tvos?

### ISSUE THREAD

**Issue by joshuaben** [rudderlabs/rudder-sdk-react-native#312]
**Is your feature request related to a problem? Please describe.**
Currently, when using tvOS with react-native via [react-native-tvos](https://github.com/react-native-tvos/react-native-tvos), the project wont compile with the following:

> Couldn't install Pods. Updating the Pods project and trying again...
> Command `pod install` failed.
> └─ Cause: The platform of the target `frontrow-tvOS` (tvOS 12.4) is not compatible with `RNRudderSdk (1.11.3)`, which does not support `tvOS`

**Describe the solution you'd like**
A target added for tvOS that allows for the same API to work on tvOS targeted react-native projects.

**Describe alternatives you've considered**
I've bumped the target, tried to use the web sdk, and started down the path of adding the sdk manually via pod.  While I am able to get the pod installed on the iOS side, there is still no bridge to the events.

**Comment by gabrieldonadel** [comment]
If so, should this also support [react-native-macos](https://github.com/microsoft/react-native-macos)?

**Comment by joshuaben** [comment]
Not sure, does Rudderstack support macOS as it does have support for tvOS.

It seems to be working with the expo version:
https://docs.expo.dev/guides/building-for-tv/

I am building for tvOS using the above and with the integration outlined here within this repo and it compiles without the above mentioned error.

**Comment by 1abhishekpandey** [comment]
Thank you for submitting this feature request. I have forwarded it to our product team for further consideration.

**Comment by 1abhishekpandey** [comment]
Hey @joshuaben, 
We have released the support for tvOS in our React Native SDK version 1.12.0: [rudder-sdk-react-native@1.12.0](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.12.0).
