### ISSUE TITLE
Traits are not resetting

### ISSUE THREAD

**Issue by hariomsharma-jmd** [rudderlabs/rudder-sdk-react-native#33]
Hi, 
I am facing one issue in RudderStack attribute tracking. If we login with one user and setting userId, attributes are tracking fine. but when logout from that user and login again with new user on same device, userId is updating in attributes but getting attribute of older user also. We are calling reset() function on logout but traits are not resetting.

Thanks

**Comment by arnab-p** [comment]
@hariomsharma-jmd We tried to reproduce the issue with the latest version of the SDK. Everything seems to be working as per expectation. I'd suggest you try out the latest version of the SDK, and if the issue persists, can you please help us with more details? Any relevant log will be highly appreciated.

**Comment by hariomsharma-jmd** [comment]
Thank you @arnab-p Its working fine after upgrading to latest version.
