### ISSUE TITLE
Feature Request: Allow retrieving anonymousId set by the sdk

### ISSUE THREAD

**Issue by haikov** [rudderlabs/rudder-sdk-react-native#332]
Hey 👋 

I have a use-case which requires getting anonymous id from the rudderstack sdk on device to pass it to another sdk as an identifier, and looks like there is no way of doing it at the moment?

Looking at the documentation, it's available on both iOS (via `[RSClient getInstance].anonymousId;`) and Android (via `RudderClient.getInstance()?.anonymousId`) but not in RN.

**Comment by 1abhishekpandey** [comment]
Hey @haikov,
Thank you for submitting this feature request. I will communicate it to our team for further consideration.

**Comment by 1abhishekpandey** [comment]
Hey @haikov,
You can retrieve the anonymousId in React Native using the following code:
```
const getRudderContext = async () => {
    const context: IRudderContext | null = await rudderClient.getRudderContext();
    const anonymousId = context.traits.anonymousId;
    console.log(`Anonymous ID: ${anonymousId}`);
};
```

**Comment by haikov** [comment]
That's exactly what I needed, thank you!

**Comment by connorpmullins** [comment]
@1abhishekpandey - I came here with the same issue. Any chance your team would be willing to update the docs with this?

**Comment by 1abhishekpandey** [comment]
Hey @connorpmullins, 
I'll definitely make sure to add this information to our document.

**Comment by 1abhishekpandey** [comment]
Hey @connorpmullins,
We have updated our doc with the steps to retrieve the anonymousId: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#retrieving-anonymous-id.

**Comment by connorpmullins** [comment]
Thank you! Our team's really enjoyed working with Rudderstack so far.
