### ISSUE TITLE
Problem with typescript implementation "This expression is not callable"

### ISSUE THREAD

**Issue by facundofernandez** [rudderlabs/rudder-sdk-react-native#35]
Hi, I am using your library in a project and I am having problems with typescript.

The compile-time message is as follows:

```
node_modules/@rudderstack/rudder-sdk-react-native/src/RudderConfiguaration.ts:39:45 - error TS2349: 
This expression is not callable.
Type 'never' has no call signatures.

typeof integration === "function" ? integration() : null
```
https://github.com/rudderlabs/rudder-sdk-react-native/blob/0dfac0c43c78f786ebd44ab40a240fb53105d627/src/NativeBridge.ts#L13

https://github.com/rudderlabs/rudder-sdk-react-native/blob/0dfac0c43c78f786ebd44ab40a240fb53105d627/src/RudderConfiguaration.ts#L39

I had to fix it with the "**patch-package**" library to add a correct type. (a new interface)

```typescript
interface Integration {
	(): void;
}


export interface Configuration {
	dataPlaneUrl?: string;
	controlPlaneUrl?: string;
	flushQueueSize?: number;
	dbCountThreshold?: number;
	sleepTimeOut?: number;
	configRefreshInterval?: number;
	trackAppLifecycleEvents?: boolean;
	recordScreenViews?: boolean;
	logLevel?: number;
	withFactories?: Array<Integration>;
}
```

**Comment by desusai7** [comment]
Hey @facundofernandez,
Can you please help us with the steps to reproduce the issue? Tried reproducing the issue in a React Native app using TypeScript, so your help would be appreciated!
