### ISSUE TITLE
BUG : AppsFlyer cloud mode issues / externalId issues

### ISSUE THREAD

**Issue by petetnt** [rudderlabs/rudder-sdk-react-native#381]
**Describe the bug**

I am trying to use the AppsFlyer Cloud mode to send events from RudderStack to AppsFlyer but I am finding the instructions confusing and data does not seem to be going to AppsFlyer.

I can correctly fetch the the `appsFlyerId` from the native module:

```ts
  const appsFlyerId = await appsFlyerNativeModule.getAppsFlyerId();
  console.log(appsFlyerId) // gives the ID correctly.
```

By RudderStack initialization looks like this:

```ts
const rudderInitialise = async () => {
  const appsFlyerId = await appsFlyerNativeModule.getAppsFlyerId();

  await rudderClient.setup(
    Config.RUDDERSTACK_KEY,
    {
      logLevel: RUDDER_LOG_LEVEL.VERBOSE,
      dataPlaneUrl: Config.RUDDERSTACK_DATA_PLANE_URL,
      trackAppLifecycleEvents: true,
      recordScreenViews: false,
    },
    {
      externalIds: [
        {
          id: appsFlyerId,
          type: 'appsFlyerExternalId'
        }
      ]
    }
  );
};
```

The events are send to RudderStack, but data is not flowing to AppsFlyer but I don't know how to debug the issue further as I don't see the `externalIds` in the event payload, not sure if it should be there in the first place, the documentation is pretty vague about this.

Sample payload from Rudderstack:

```json
{
    "anonymousId": "9de3459c-854f-4688-b479-1301a920cdee",
    "channel": "mobile",
    "context": {
        "app": {
            "build": "58",
            "name": "Foo",
            "namespace": "com.foobar.com",
            "version": "1.0.7"
        },
        "device": {
            "attTrackingStatus": 0,
            "id": "139f7f31-d772-4ef3-9191-07fa496b640e",
            "manufacturer": "Apple",
            "model": "x86_64",
            "name": "iPhone 15 Pro",
            "type": "iOS"
        },
        "library": {
            "name": "rudder-ios-library",
            "version": "1.29.0"
        },
        "locale": "en-FI",
        "network": {
            "cellular": false,
            "wifi": true
        },
        "os": {
            "name": "iOS",
            "version": "17.4"
        },
        "screen": {
            "density": 3,
            "height": 852,
            "width": 393
        },
        "sessionId": 1728376201,
        "timezone": "Europe/Helsinki",
        "traits": {
            "anonymousId": "9de3459c-854f-4688-b479-1301a920cdee"
        }
    },
    "event": "RewardCode",
    "integrations": {
        "All": true
    },
    "messageId": "01e91216-beb7-4d60-a66f-5bd388cca870",
    "originalTimestamp": "2024-10-08T08:35:06.812Z",
    "properties": {
        "name": "RewardCode"
    },
    "receivedAt": "2024-10-08T08:35:07.807Z",
    "request_ip": "89.27.52.57",
    "rudderId": "259c9cc0-7ec2-4131-a2ba-ab5ceb18b15b",
    "sentAt": "2024-10-08T08:35:07.613Z",
    "type": "screen"
}
```

Looking at the docs, we can see that the example uses `appsflyerExternalId` while the description shows `appsFlyerExternalId`

<img width="803" alt="image" src="https://github.com/user-attachments/assets/09fe5cb8-719f-4368-b123-3fe29cda1a45">

To make matters worse, the documentation uses the following versions of the `externalId` field across the docs:

```ts
// externalIds with array of objects
externalIds: [{
  id: appsFlyerId,
  type: 'appsFlyerExternalId'
}]

// externalId with a single object:
externalId: {
   id: appsFlyerId,
  type: 'appsFlyerExternalId'
}

// externalId with array of objects:
externalId: [{
   id: appsFlyerId,
  type: 'appsFlyerExternalId'
}]
```

Here it says that `externalIds` is supported as a legacy option:

https://github.com/rudderlabs/rudder-sdk-react-native/blob/5637c37d146f931d0beed8ffa2c4c38c861172ff/libs/sdk/ios/RNRudderSdkModule.m#L253-L263

but `externalIds` is used right here in the main documentation: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#setting-custom-id

My *main questions* are:

- How to confirm that the `appsFlyerExternalId` is correctly sent to Rudderstack
- What's the correct format for `externalIds`

**Which platform is the issue occurring on**
Is the error occurring on:

Version:
```package
@rudderstack/rudder-sdk-react-native": "^1.14.0"
```

- [x] Android
- [x] iOS
- [x] Both Android and iOS

**To Reproduce**
Steps to reproduce the behaviour:

1. Fetch `appsFlyerId` from the appsFlyerModule
1. Initialise React-Native SDK as mentioned above
2. Send events

**Expected behavior**
The events are delivered to the linked appsFlyerModule

** Actual behavior**

The events are not delivered and I have no idea how to debug this further. 

**Screenshots**

**Version of the _React-Native_ SDK**
Please provide the following information:

1. The version of the Rudder React-Native SDK you are using (e.g., Rudder React-Native SDK v1.0.0)
```
@rudderstack/rudder-sdk-react-native": "^1.14.0"
```

3. The versions of the Rudder Android and iOS SDKs utilized within React-Native (e.g., Rudder Android SDK v1.0.0 and Rudder iOS SDK v1.0.0)

```
RNRudderSdk (1.14.0):
```

same for Android.
**SDK initialisation snippet**
Share the code snippet used for initializing the React-Native SDK.

```ts
const rudderInitialise = async () => {
  const appsFlyerId = await appsFlyerNativeModule.getAppsFlyerId();

  await rudderClient.setup(
    Config.RUDDERSTACK_KEY,
    {
      logLevel: RUDDER_LOG_LEVEL.VERBOSE,
      dataPlaneUrl: Config.RUDDERSTACK_DATA_PLANE_URL,
      trackAppLifecycleEvents: true,
      recordScreenViews: false,
    },
    {
      externalIds: [
        {
          id: appsFlyerId,
          type: 'appsFlyerExternalId'
        }
      ]
    }
  );
};
```

**Framework version of the SDK**
Please indicate the version of the React-Native framework used (e.g., “react-native”: v0.70.6).

```
"react-native": "0.75.3" 
```

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
Confirm that the correct `writeKey` and `dataPlaneUrl` are utilized during SDK initialization.

🆗 ✅

**Comment by petetnt** [comment]
After posting this issue I started getting the following error on RudderStack:

```
{
  "error": "Appsflyer id is not set. Rejecting the event"
}
```

The same event was working just find when I posted this issue with same configuration 

<img width="716" alt="image" src="https://github.com/user-attachments/assets/ee5ad166-b3a5-409d-8fa1-79e86a08087d">

<img width="817" alt="image" src="https://github.com/user-attachments/assets/1ecc677f-f16b-4678-a259-5d7141ff9d1c">


🫨

**Comment by 1abhishekpandey** [comment]
Hey @petetnt,

Please refer to our React Native doc for the steps to set externalId in React Native: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#setting-custom-id.
```
const options = {
  externalIds: [
    {
      id: "<external_id>",
      type: "appsFlyerExternalId",
    },
  ],
}
rudderClient.identify(
  "1hKOmRA4GRlm",
  {
    email: "alex@example.com",
    location: "UK",
  },
  options
)
```

**NOTE**: ExternalId can only be set using `identify` events and once set this will persist across the events until the `reset` call is made and you can see this in the actual event payload under `context`.

**Comment by petetnt** [comment]
@1abhishekpandey in the documentation it says that `identify` cannot be used with `cloud mode`:

<img width="810" alt="image" src="https://github.com/user-attachments/assets/e4ca7e97-57c6-4d8e-ab36-9d8b07543be5">

https://www.rudderstack.com/docs/destinations/streaming-destinations/appsflyer/

**Comment by 1abhishekpandey** [comment]
The `identify` event is needed to set the `externalId` in the context from the React Native side. If that is not supported in AppsFlyer cloud mode, I'm expecting to be safely rejected.

I can see in the AppsFlyer cloud mode code, it'll reject the `identify` events, refer [here](https://github.com/rudderlabs/rudder-transformer/blob/e03ca09455c132aec82e5d2253a1655246a6c94b/src/v0/destinations/af/transform.js#L264).

**Comment by 1abhishekpandey** [comment]
There is an alternate option, you can pass the required value while SDK initialisation, refer to this doc: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#setting-custom-context and use `transformation` to convert the value in the required format: https://www.rudderstack.com/docs/transformations/overview/.

**Comment by petetnt** [comment]
After changing it to `appsflyerExternalId` (note that the capitalized version is used in the docs too and probably should be fixed), I am seeing the following error when viewing the `Appsflyer destination` events:

```
{
  "response": "redacted due to unsupported content-type",
  "firstAttemptedAt": "2024-10-08T10:17:16.287Z",
  "content-type": "application/octet-stream",
  "routerSubStage": "router_dest_delivery",
  "payloadStage": "router_input"
}
```

**Comment by petetnt** [comment]
Here's the payload it's trying to send:

```json
{
    "body": {
        "XML": {},
        "FORM": {},
        "JSON": {
            "ip": "89.27.52.57",
            "os": "17.4",
            "att": 0,
            "idfv": "139f7f31-d772-4ef3-9191-07fa496b640e",
            "eventName": "screen",
            "eventTime": "2024-10-08T10:20:49.709Z",
            "eventValue": "{\"name\":\"RewardCode\"}",
            "appsflyer_id": "1725356348180-1397317",
            "sharing_filter": "all",
            "app_version_name": "1.0.7",
            "bundleIdentifier": "com.x",
            "customer_user_id": "eede5cf6-49e8-4864-b214-c28545265cc4"
        },
        "JSON_ARRAY": {}
    },
    "type": "REST",
    "files": {},
    "method": "POST",
    "params": {},
    "userId": "",
    "headers": {
        "Content-Type": "application/json",
        "authentication": "vegd7ZQCLsTv6SeR7X6erD"
    },
    "version": "1",
    "endpoint": "https://api2.appsflyer.com/inappevent/id1667809195"
}
```

**Comment by petetnt** [comment]
Here's the payload it is sending:

```json
{
    "body": {
        "XML": {},
        "FORM": {},
        "JSON": {
            "ip": "89.27.52.57",
            "os": "17.4",
            "att": 0,
            "idfv": "139f7f31-d772-4ef3-9191-07fa496b640e",
            "eventName": "screen",
            "eventTime": "2024-10-08T10:20:49.709Z",
            "eventValue": "{\"name\":\"RewardCode\"}",
            "appsflyer_id": "1725356348180-1397317",
            "sharing_filter": "all",
            "app_version_name": "1.0.7",
            "bundleIdentifier": "com.x",
            "customer_user_id": "eede5cf6-49e8-4864-b214-c28545265cc4"
        },
        "JSON_ARRAY": {}
    },
    "type": "REST",
    "files": {},
    "method": "POST",
    "params": {},
    "userId": "",
    "headers": {
        "Content-Type": "application/json",
        "authentication": "x"
    },
    "version": "1",
    "endpoint": "https://api2.appsflyer.com/inappevent/id1667809195"
}

```

**Comment by 1abhishekpandey** [comment]
I’m not familiar with how AppsFlyer cloud mode works. I’ll request you to raise an issue there (https://github.com/rudderlabs/rudder-transformer), as it’s managed by a different team.

**Comment by 1abhishekpandey** [comment]
We are closing this issue as there is nothing further to be done on our side.

**Comment by petetnt** [comment]
Thanks, could you ping your colleagues to answer the other issue @1abhishekpandey , this is blocking our application launch and I am seriously considering moving away from Rudderstack if the issue can't be resolved :/

**Comment by 1abhishekpandey** [comment]
I've requested them to look into it.
