### ISSUE TITLE
Version 1.0.8 does not compile on iOS

### ISSUE THREAD

**Issue by enahum** [rudderlabs/rudder-sdk-react-native#48]
It seems that 1.0.8 was not published properly or something is wrong in the native module code

https://github.com/rudderlabs/rudder-sdk-react-native/blob/master/ios/RNRudderSdkModule.m#L54 throws an error
![image](https://user-images.githubusercontent.com/6757047/120222513-0d18ec80-c20e-11eb-9d4a-8e91179a7b13.png)

**Comment by enahum** [comment]
1.0.9 same issue

**Comment by enahum** [comment]
FYI @desusai7.

Also it would be good to look at the dependabot PR's

**Comment by Manashi-1881** [comment]
this seems like, Rudder iOS pods is not installed properly. can you please delete the pods Folder and podfFile.lock file and install pods again and run after clearing the iOS app.

**Comment by enahum** [comment]
Alright, after Removing Podfile.lock this now works..

I wonder why is not picking up the pod that matches the version. Maybe something in the podspec that needs updating?

Feel free to close the issue but I would recommend looking at how to avoid this from happening again and having the podspec resolving to the right pod version

**Comment by desusai7** [comment]
Hey @enahum ,
Yeah, we will take a look at the dependabot PR's and also work on the podspec to make sure this is fixed. 
Closing this issue,
Thank you :)
