### ISSUE TITLE
Device Token Registration on lifecycle events 

### ISSUE THREAD

**Issue by twom** [rudderlabs/rudder-sdk-react-native#5]
Hi,

We started an implementation of the rudder react native sdk and we are looking for some advice on adding device token the the lifecycle events.

The documentation refers to iOS and Android native code: https://docs.rudderstack.com/destinations/customer.io
However, it is unclear what the approach  would be in the react-native sdk.

Any pointers or documentation updates would be appreciated.  I will update this issue too if we figure it out ourselves :)

**Comment by arnab-p** [comment]
Hi @twom ,

We don't have support for adding the device token in our react-native SDK now. We are planning to add it. It'll be done in a couple of week.

**Comment by twom** [comment]
thank you @arnab-p  ... for now we will use the customer.io API directly in our app to send the device token.
