### ISSUE TITLE
Does Amplitude device mode work with this library?

### ISSUE THREAD

**Issue by gilbertl** [rudderlabs/rudder-sdk-react-native#65]
I see that Rudderstack supports device mode for Amplitude via iOS and Android libraries. Do those work with react native integration?

**Comment by desusai7** [comment]
We have added support for the Amplitude and Braze Device Mode just now. 

[Here](https://www.npmjs.com/package/@rudderstack/rudder-integration-amplitude-react-native) it is: Rudder Amplitude React Native Device Mode
