### ISSUE TITLE
Amplitude integration: how to override anonymousId (which send to AM as "device_id")

### ISSUE THREAD

**Issue by twom** [rudderlabs/rudder-sdk-react-native#7]
Hi, 

We have a scenario where we are tracking events happening on an in-store kiosk. This means that multiple users will go sequentially through this flow:

- go to the kiosk as an anonymous user
- do actions + start checkout
- enter phone number (which gives us a userId)
- finish checkout
---> new users will repeat the above flow

the (small) problem is that, when a new user starts an anonymous session, Amplitude will link these actions with the "last known userId that used the same deviceId. Which in this scenario does not make sense as there is 1 device for multiple users.

The easy fix would be to create a dynamic anonymousId in the Rudder client each time a user comes to the kiosk. As far as we understand the anonymousId is mapped back to the device_id field send to amplitude.

We have tried different ways of overriding this, so Amplitude can receive a device id within our control. It may be that the RN Rudder Client does not allow overriding the anonymousId and always defaults to the deviceId?

Any advice?

Thank

**Comment by dhawal1248** [comment]
Hey @twom ,we have been working on this.
Will release this for all our SDKs in a couple of weeks.

**Comment by arnab-p** [comment]
@twom We've released this feature for the ReactNative SDK. You can refer to this document: https://docs.rudderstack.com/stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk#anonymous-id
