### ISSUE TITLE
Very old react-native peer dependency

### ISSUE THREAD

**Issue by WorldSeso7** [rudderlabs/rudder-sdk-react-native#85]
Please update the sdk to work with other react-native versions.
Now this package works only with 
"peerDependencies": {
    "react-native": "0.41.2"
  },
but react-native at this moment is at version 0.67.2 and version 0.41.2 was released on 6th feb 2017

**Comment by desusai7** [comment]
Hey @WorldSeso7,

We are looking into this, you will have a fix deployed soon.

**Comment by AliHaidar110** [comment]
same issue

**Comment by desusai7** [comment]
@AliHaidar110 , We will have the fix released today

**Comment by desusai7** [comment]
@AliHaidar110  @WorldSeso7  We've released a fix for this issue in version 1.1.2. Please upgrade to it. 
Thank you
